spring:
  application:
    name: Ecommerce
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
#  sql:
#    init:
#      mode: always