package com.DipYukti.Ecommerce.type;

public enum PermissionType
{
    READ_CUSTOMER,
    CREATE_CUSTOMER,
    UPDATE_CUSTOMER,
    DELETE_CUSTOMER,
    READ_PRODUCT,
    CREATE_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,
    READ_ORDER,
    CREATE_ORDER,
    UPDATE_ORDER,
    DELETE_ORDER,
    CHANGE_PASSWORD,
    READ_CART,
    UPDATE_CART,
    DELETE_CART,
    READ_CATEGORY,
    UPDATE_CATEGORY,
    DELETE_CATEGORY,
    CREATE_CART,
    CREATE_CATEGORY,
    CLEAR_CART

}


